### ISSUE TITLE
HPXML meta-measure

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BEopt#137]
TODO:
- [x] Needs error handling for paths/files that don't exist.
- [ ] If user doesn't specify weather file path, fall back on "nearest weather file" using:
  - [ ] https://developer.nrel.gov/docs/solar/data-query-v1/
  - [x] lookups for zip, city, and/or state [current approach]
- [x] Workflow measure order according to measure-info.json
- [ ] Geometry (see #138)
- [ ] Options (populate measure arguments)
  - [ ] What if we have heating / cooling setup / setback values but not the times of weekday / weekend?
  - [ ] How to deal with multiple hvac heating systems?
  - [ ] How to deal with multiple appliances of the same type?
  - [ ] How to deal with multiple walls having different properties?
  - [ ] Some HPXML elements have, e.g., efficiency=0. Does this indicate missing data or NA?
- [x] Require weather file path (remove epw lookup)
- [x] Allow mobile homes
- [x] Update measure calls to look like Scott's
- [ ] Clean up geometry portion (make more hierarchical)
- [ ] Hot water, lighting, appliances, misc - RESNET-specific measures that differ from ours
- [ ] Like-element aggregations vs mods to measures - e.g., area-weighted averaging vs wall construction to handle more than one set of properties for multiple walls

**Comment by shorowit** [comment]
Hmm, I would think we'd prefer to simply have an argument for the epw file path, which would get passed through to the Location measure. Though we could make the argument optional and use this code as a backup.

**Comment by shorowit** [comment]
Will address as part of #154
